languages:
  supported_source_languages:
    - English
    - Farsi
    - Spanish
    - French
    - German
    - Italian
    - Japanese
    - Korean
    - Portuguese
    - Russian
    - Chinese
    - Turkish
    - Arabic
    - Hindi

  supported_proficiency_levels:
    - A1
    - A2
    - B1
    - B2
    - C1
    - C2

prompt:
  system_message: |
    Translate the given word (whether it is in German or {source_language}) to the corresponding counterpart, adding detailed grammatical information, and generate three usage examples at the {proficiency_level} level following specific guidelines for different types of words.
    # Steps

    1. **Determine Type of Word**: Classify the given word as either a noun, verb, adjective, or 'none of the above'.

    2. **Translate the Word**: Translate the provided word into its accurate equivalent in the other language (German to {source_language} or {source_language} to German).

    3. **Grammatical Information**:
        - *If the word is a noun*:
          - Indicate that the word is a noun with '(n)'.
          - Provide the appropriate definite article ('der', 'die', 'das' for German).
          - Include the plural form.
        - *If the word is a verb*:
          - Indicate that the word is a verb with '(v)'.
          - Provide the verb conjugations: Infinitive, Präsens, Präteritum, Perfekt for all forms in German (ich, du, er/sie/es, wir, ihr, sie/Sie).
        - *If the word is an adjective*:
          - Indicate that the word is an adjective with '(adj)'.
        - *If the word is none of the above*:
          - Indicate that the word is none of them with '()'.

    4. **Generate Examples**: Provide three example sentences showing a typical usage of the word. These examples must be at the {proficiency_level} language proficiency level:
       - **Example in German**: Create an example sentence in German.
       - **Translation in {source_language}**: Translate the example sentence into {source_language}.

    # Output Format

    The output should be presented as follows:

    - **Original Word**: [Provided Word]
    - **German Word**: [Translated German Word without the article]
    - **Classification**: (n) / (v) / (adj) or ()
    - **{source_language} Translation**: [Equivalent Word in {source_language}]
    - **Additional Grammatical Information**:
      - *For Nouns*: Article, Plural Form
      - *For Verbs*: Infinitive, Präsens, Präteritum, Perfekt (provide conjugations for ich, du, er/sie/es, wir, ihr, sie/Sie - no need to mention ich, du, er/sie/es, wir, ihr, sie/Sie themselves, make sure to keep the order)
    - **Examples**:
      - 1. German Example: [Sentence in German]
        - {source_language} Example Translation: [Translation of the German Example Sentence]
      - 2. German Example: [Sentence in German]
        - {source_language} Example Translation: [Translation of the German Example Sentence]
      - 3. German Example: [Sentence in German]
        - {source_language} Example Translation: [Translation of the German Example Sentence]
    - The example sentences should be in {proficiency_level} level to ensure they are appropriate for {proficiency_level} level learners. This will help ensuring the examples maximize their learning experience.
    - When generating examples, take into account the proficiency level ({proficiency_level}). Ensure word choice and grammatical complexity match the target learner's level.
    - If the word has multiple meanings or uses, choose the most common interpretation.

openai:
  text_model: "gpt-4o-mini"
  image_model: "dall-e-3"
  image_size: "1024x1024"
  tts_model: "tts-1"

schema:
  type: object
  properties:
    original_word: { type: string }
    german_word: { type: string }
    classification: 
      type: string 
      enum: ["(n)", "(v)", "(adj)", "()"]
    source_language_translation: { type: string }
    additional_grammatical_info:
      type: object
      properties:
        noun:
          type: object
          properties:
            article: 
              type: string 
              enum: ["der", "die", "das"]
            plural_form: { type: string }
        verb:
          type: object
          properties:
            infinitive: { type: string }
            praesens: 
              type: array 
              items: { type: string }
            praeteritum: 
              type: array 
              items: { type: string }
            perfekt: 
              type: array 
              items: { type: string }
        adjective:
          type: object
          properties: {}
    examples:
      type: array
      minItems: 3
      maxItems: 3
      items:
        type: object
        properties:
          german_example: { type: string }
          source_example_translation: { type: string }
        required: ["german_example", "source_example_translation"]
  required: ["original_word", "german_word", "classification", "source_language_translation", "examples"]

files:
  directory: "./files"

anki:
  deck_name: "Test Anki Connect3"
  model_name: "Custom_German_Learning"
  connect_url: "http://localhost:8765"
  card_templates:
    - Name: "Card 1 DE->SL"
      Front: "{{Wort_DE}}{{Wortarten}}{{Audio_Wort}}"
      Back: |
        {{#Artikel}}{{Artikel}}{{/Artikel}}
        {{Wort_DE}}{{Wortarten}}
        {{#Plural}}{{Plural}}{{/Plural}}
        <div>{{Picture}}</div>
        <div style='font-family: Arial; font-size: 16px;'>
        {{#Praesens}}<br>Präsens: {{Praesens}}{{/Praesens}}
        {{#Praeteritum}}<br>Präteritum: {{Praeteritum}}{{/Praeteritum}}
        {{#Perfekt}}<br>Perfekt: {{Perfekt}}{{/Perfekt}}
        </div>
        <hr id=answer>
        {{Wort_SL}}
        <hr>
        <div style="display:none">[sound:_LongSilence.mp3]</div>
        {{#Satz1_DE}}
        <div style='font-family: Arial; font-size: 16px;'>{{Satz1_DE}}{{Audio_S1}}</div>
        <div style='font-family: Arial; font-size: 14px;'>{{Satz1_SL}}</div><br>
        {{/Satz1_DE}}
        {{#Satz2_DE}}
        <div style='font-family: Arial; font-size: 16px;'>{{Satz2_DE}}{{Audio_S2}}</div>
        <div style='font-family: Arial; font-size: 14px;'>{{Satz2_SL}}</div><br>
        {{/Satz2_DE}}
        {{#Satz3_DE}}
        <div style='font-family: Arial; font-size: 16px;'>{{Satz3_DE}}{{Audio_S3}}</div>
        <div style='font-family: Arial; font-size: 14px;'>{{Satz3_SL}}</div><br>
        {{/Satz3_DE}}

    - Name: "Card 2 SL->DE"
      Front: "{{Wort_SL}}"
      Back: |
        {{Wort_SL}}
        <hr id=answer>
        {{#Artikel}}{{Artikel}}{{/Artikel}}
        {{Wort_DE}}{{Wortarten}}
        {{#Plural}}{{Plural}}{{/Plural}}
        {{Audio_Wort}}
        <div>{{Picture}}</div>
        <div style='font-family: Arial; font-size: 16px;'>
        {{#Praesens}}<br>Präsens: {{Praesens}}{{/Praesens}}
        {{#Praeteritum}}<br>Präteritum: {{Praeteritum}}{{/Praeteritum}}
        {{#Perfekt}}<br>Perfekt: {{Perfekt}}{{/Perfekt}}
        </div>
        <hr>
        <div style="display:none">[sound:_LongSilence.mp3]</div>
        {{#Satz1_SL}}
        <div style='font-family: Arial; font-size: 16px;'>{{Satz1_SL}}</div>
        <div style='font-family: Arial; font-size: 14px;'>{{Satz1_DE}}{{Audio_S1}}</div><br>
        {{/Satz1_SL}}
        {{#Satz2_SL}}
        <div style='font-family: Arial; font-size: 16px;'>{{Satz2_SL}}</div>
        <div style='font-family: Arial; font-size: 14px;'>{{Satz2_DE}}{{Audio_S2}}</div><br>
        {{/Satz2_SL}}
        {{#Satz3_SL}}
        <div style='font-family: Arial; font-size: 16px;'>{{Satz3_SL}}</div>
        <div style='font-family: Arial; font-size: 14px;'>{{Satz3_DE}}{{Audio_S3}}</div><br>
        {{/Satz3_SL}}

